### ISSUE TITLE
esp8266 libraries 

### ISSUE THREAD

**Issue by alexdisoza007** [sweetim/ESP8266-STM32F4Discovery#1]
Hi, 
Is this project work on ESP 8226-01? bcz you mentioned both ESP 8266-01 and  ESP-12-Q, I am getting confusion , also i couldn't find esp related libraries.  

Regards, 
Alex

**Comment by sweetim** [comment]
as far as i know, both of these modules are the same
and this repo does not contain ESP 8226-01 driver library, it is just a quick way to check the connectivity between the STF4Discovery and with the chip

**Comment by Gadag007** [comment]
Ok thanks , your code is working fine .
